### ISSUE TITLE
Maybe use composer merge plugin 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_elections_reporting#5]
Thanks for all the work on this! Keen to take it for a spin soon.

In the mean time, I was just reading the README.md and note the need for additional external libraries: https://github.com/localgovdrupal/localgov_elections_reporting?tab=readme-ov-file#before-installing

Webform deals with this with the composer merge plugin, see: 

https://www.drupal.org/docs/8/modules/webform/webform-frequently-asked-questions/how-to-use-composer-to-install-libraries-for-the-webform-module

Might we want to do the same, and define a composer.libraries.json in this module for easier inclusion?

**Comment by chriswales95** [comment]
Hi @finnlewis, I think this is a good idea. We didn't have time when we put the first release out to investigate the plugin but we were aware that Webform handled it in some way. 

I think it's definitely something to look into and get into the first proper release :). I agree the setup at the moment is a bit fiddly due to the external libraries.

**Comment by chriswales95** [comment]
Hi @finnlewis, I don't see a way to make the merge plugin work. It doesn't seem to work if it's not in the root composer. I think it must be to do with how the order of it all works. Plus a lot of the docs online say that it isn't favoured much these days and it's a big issue because the plugin doesn't seem to be invoked early enough which is a shame.

I think we've found another way forward in this issue #25. The charts library has a CDN option which means we can remove the composer dependency. If a motivated user wants to, they could change this and then get the highcharts library another way if they didn't want the CDN. This seems in step with webform who follow a similar method with CDNs.
