### ISSUE TITLE
Rename social post module

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_elections_reporting#62]
All the submodules in this repo are namespaced with `localgov_elections_*` execpt the social post module with uses `localgov_election_...` (singular).

**Comment by msayoung** [comment]
Should they all be namedspaced `localgov_elections_reporting_` as that's the name of the parent module?

**Comment by markconroy** [comment]
I think we might be a bit close to the end of the project for such a large change.

**Comment by finnlewis** [comment]
> Should they all be namedspaced `localgov_elections_reporting_` as that's the name of the parent module?

I was thinking the same, but can't find any definitive documentation to that effect. 

Webform certainly follows that approach: https://git.drupalcode.org/project/webform/-/tree/6.2.x/modules?ref_type=heads

And Metatag: https://git.drupalcode.org/project/metatag

Naming things is always difficult, but consistency is important. So if we're going to do any renaming, we might want to get it all aligned now before a stable release.

We also need to watch out for the 50 character limit: https://www.drupal.org/docs/develop/creating-modules/naming-and-placing-your-drupal-module

**Comment by finnlewis** [comment]
@dedavidson @markconroy I'm really keen to make sure these sub-modules are named following the convention:

`[parent_module_name]_[sub_module_name]`

As far as I can find, this is a convention rather than a standard, but it makes a lot of sense to avoid namespace conflicts and @ekes confirmed this as expected naming conventions when we touched on it in Merge Tuesday today.

Happy to help do this and test this rapidly if we can.

**Comment by markconroy** [comment]
@finnlewis `localgov_elections_social_post` is now renamed to `localgov_elections_reporting_social_post`
